spring:
  application:
    name: lwa-search-engine
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      discovery:
        enabled: true

server:
  address: ${lwa.server.address:0.0.0.0}
  port: ${lwa.server.port:8010}
  forward-headers-strategy: native
  servlet:
    context-path: /search-engine/
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    whitelabel:
      enabled: false

logging:
  level:
    root: ERROR
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}%L){blue} %clr(:){red} %clr(%m){faint}%n"
    file: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}%L){blue} %clr(:){red} %clr(%m){faint}%n"
  file:
    path: /logs/

application-description: Search-Engine
application-version: v1.0

